
services:
  web:
    build: .
    platform: linux/arm64/v8
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8080:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:567234@db:5432/app_db
      REDIS_URL: redis://redis:6379/0
      FROM_EMAIL: no-reply@example.com
      SECRET_KEY: supersecret
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
      MAIL_HOST: host.docker.internal
      MAIL_PORT: 1025
    depends_on:
      - db
      - redis
      - mailhog
  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    restart: always
    ports:
      - "1025:1025"   # SMTP (куди відправляє FastAPI)
      - "8025:8025"   # WEB-інтерфейс (де дивишся листи)

  db:
    image: postgres:16
    platform: linux/arm64/v8
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    platform: linux/arm64/v8
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
